# This is a basic workflow to help you get started with Actions

name: CI
   
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  widoco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         ref: main
         path: main
      - name: Build HTML for main
        run: |
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-11.jar
           mkdir public
           cp main/index.html public/index.html
           mkdir public/pods
           mkdir public/mainzed
           mkdir public/aligment
           java -jar widoco.jar -ontFile main/PODS_1_1_7.ttl -outFolder public/pods -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           java -jar widoco.jar -ontFile main/PODS_1_1_8_Mainzed.ttl -outFolder public/mainzed -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
           target_branch: gh-pages
           build_dir: public/
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This workflow contains a single job called "build"  
  build: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    needs: widoco
    with: 
        version: v018
        rdffilepath: PODS_1_1_7.ttl
        docpath: docs
        prefixns: https://photogrammetry.altervista.org/collections/show/3
        prefixnsshort: pods
        indexpages: true
        ckan: false
        metadatatable: true
        offlinecompat: false
        exports: cypher graphml nt n3 tlp tgf json ttl
        createcollections: true
        createnonNSPages: true
        createVOWL: true
        preferredlang: en
        ghpagesfolder: ontdoc
        ghpages: true
